openapi: 3.0.0
info:
  title: Product API
  description: API to retrieve product information
  version: 1.0.0
paths:
  /product/{product_id}/price:
    get:
      summary: Get price of a product
      description: Returns the pricing information of a product for a chain of stores on a specific date.
      tags:
        - Price
      parameters:
        - name: productId
          in: path
          description: The identifier of the product to retrieve prices for.
          required: true
          schema:
            type: string
        - name: date
          in: query
          description: The date on which the price should be retrieved (format YYYY-MM-DD hh:mm:ss).
          required: true
          schema:
            type: string
            format: date
        - name: brandId
          in: query
          description: The identifier of the chain of stores to retrieve prices for.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  productId:
                    type: string
                    description: The identifier of the product requested.
                  brandId:
                    type: string
                    description: The identifier of the chain of stores requested.
                  tariff:
                    type: number
                    description: The tariff to apply on the requested date.
                  startDate:
                    type: string
                    format: date
                    description: The start date of the rate application.
                  endDate:
                    type: string
                    format: date
                    description: The end date of the rate application.
                  price:
                    type: number
                    description: The final price to apply to the product on the requested date.
        '400':
          description: Invalid request
        '500':
          description: Internal server error
